apiVersion: v1
kind: Pod
metadata:
  name: blocked-client
  namespace: secure-apps
  labels:
    access: blocked
spec:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: client
      image: curlimages/curl:latest
      command: ["sleep", "3600"]
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        runAsUser: 100
        runAsGroup: 101
